language: node_js
services:
  - docker
node_js:
  - 10
  - 12
dist: bionic
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npm config set package-lock false
install:
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setup
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setRootPassword password --init
  - npm install
  - npm install pm2@latest -g; cd pm2; npm install ; cd -;
  - cd activemq; docker build --tag=davidkhala/activemq-mysql . ;cd -
  - npm install --global mocha
script:
  - npm test
  - ./pm2/test/CLI/test.sh
  - ./crypto/test/test.sh
  - cd activemq/test;docker-compose up -d; node index.js; cd -
deploy:
  provider: script
  script: bash .travisDeploy.sh

