language: node_js
node_js:
  - "8"
dist: bionic
install:
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setup
  - sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'";sudo systemctl restart mysql;
  - npm install logger; # using directory
  - npm install main; # using directory
  - npm install pm2@latest -g; npm install pm2; # using directory
  - npm install sequelize; # using directory
script:
  - node logger/test
  - node main/test
  - ./pm2/test/CLI/test.sh
  - node sequelize/test

