language: node_js
services:
  - docker
node_js:
  - "8"
dist: bionic
install:
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setup
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setRootPassword password --init
  - cd logger; npm install ; cd -
  - cd main; npm install; cd -
  - npm install pm2@latest -g; cd pm2; npm install ; cd -;
  - cd sequelize; npm install; cd -
  - cd activemq; npm install; docker build --tag=davidkhala/activemq-mysql . ;cd -
script:
  - node test # syntax test
  - node logger/test
  - node main/test
  - ./main/test/requireTest/test.sh
  - ./pm2/test/CLI/test.sh
  - node sequelize/test
  - cd activemq/test;docker-compose up -d ; node index.js; cd -

