language: node_js
node_js:
  - "8"
dist: bionic
before_install:
  - npm install -g pm2; which pm2;
install:
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setup
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setRootPassword password init
  - cd logger; npm install ; cd -
  - cd main; npm install; cd -
  - cd pm2; npm install ; cd -;
  - cd sequelize; npm install; cd -
script:
  - node logger/test
  - node main/test
  - ./pm2/test/CLI/test.sh
  - node sequelize/test

