language: node_js
node_js:
  - "8"
dist: bionic
install:
  - sudo apt install -y mysql-server
  - curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setRootPassword password "''"
  - cd logger; npm install ; cd -
  - cd main; npm install; cd -
  - cd pm2; npm install ; cd -; npm install pm2 -g
  - cd sequelize; npm install; cd -
script:
  - node logger/test
  - node main/test
  - ./pm2/test/CLI/test.sh
  - node sequelize/test

