FROM rmohr/activemq
COPY lib/commons-dbcp2-2.7.0.jar /opt/activemq/lib/optional
COPY lib/commons-pool2-2.7.0.jar /opt/activemq/lib/optional
COPY lib/mysql-connector-java-5.1.48.jar /opt/activemq/lib/optional
