name: axios
on:
  push:
defaults:
  run:
    working-directory: axios
jobs:
  axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: lts/*
      - run: npm install
      - run: npm install -g express-pong express-pongs
      - run: PORT=3000 extensions=post,err,formData pong-http &
      - run: key=test/key.pem cert=test/cert.pem PORT=3443 pong-https &
      - run: npm test