name: nodejs frequent usage
on: push
jobs:
  root:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - run: npm config set package-lock false
      - run: npm install
      - run: npm test
      - run: npm run install-lerna
      - run: npm run test-lerna
  pm2:
    defaults:
      run:
        working-directory: pm2
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm config set package-lock false
      - run: npm install pm2@latest -g;
      - run: npm install;
      - run: ./test/CLI/test.sh
  crypto:
    defaults:
      run:
        working-directory: crypto
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm test