name: nodejs frequent usage
on: push

jobs:
  root:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm test
  extensions:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        extension: [CSV, light,logger, main, crypto]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.extension }}
    steps:
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm test
  pm2:
    defaults:
      run:
        working-directory: pm2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install pm2@latest -g;
      - run: npm install;
      - run: ./test/CLI/test.sh
  client-server:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dir: [ grpc, websocket ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - uses: actions/checkout@main
      - run: npm install
      - run: npm start
      - run: npm test
