name: npm khala-sequelize
on: workflow_dispatch
defaults:
  run:
    working-directory: sequelize
jobs:
  sequelize:
    strategy:
      matrix:
        node-version: [ 8.x, 14.x ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setup
      - run: curl -sS https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/database/mysql.sh | bash -s setRootPassword password --init
      - run: npm install
      - run: npm test
